// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AggregateHosts(arg1, arg2) {
  return window['go']['main']['App']['AggregateHosts'](arg1, arg2);
}

export function AssignIP(arg1, arg2) {
  return window['go']['main']['App']['AssignIP'](arg1, arg2);
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function DeviceHints(arg1) {
  return window['go']['main']['App']['DeviceHints'](arg1);
}

export function DismissHint(arg1) {
  return window['go']['main']['App']['DismissHint'](arg1);
}

export function ExportImage(arg1) {
  return window['go']['main']['App']['ExportImage'](arg1);
}

export function ExportMap(arg1, arg2) {
  return window['go']['main']['App']['ExportMap'](arg1, arg2);
}

export function Legend() {
  return window['go']['main']['App']['Legend']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function LoadDriftModel(arg1, arg2) {
  return window['go']['main']['App']['LoadDriftModel'](arg1, arg2);
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function LoadReconcileModel(arg1, arg2) {
  return window['go']['main']['App']['LoadReconcileModel'](arg1, arg2);
}

export function PickAssetCSV() {
  return window['go']['main']['App']['PickAssetCSV']();
}

export function RunScan(arg1) {
  return window['go']['main']['App']['RunScan'](arg1);
}

export function SaveDevice(arg1, arg2) {
  return window['go']['main']['App']['SaveDevice'](arg1, arg2);
}

export function SetLabels(arg1, arg2) {
  return window['go']['main']['App']['SetLabels'](arg1, arg2);
}

export function SetRole(arg1, arg2) {
  return window['go']['main']['App']['SetRole'](arg1, arg2);
}

export function SuggestTags(arg1) {
  return window['go']['main']['App']['SuggestTags'](arg1);
}

export function UnassignIP(arg1) {
  return window['go']['main']['App']['UnassignIP'](arg1);
}
