// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Legend() {
  return window['go']['main']['App']['Legend']();
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function RunScan(arg1) {
  return window['go']['main']['App']['RunScan'](arg1);
}
