// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mapview} from '../models';
import {main} from '../models';
import {escli} from '../models';
import {devices} from '../models';
import {snapshot} from '../models';
import {scan} from '../models';
import {assist} from '../models';

export function AggregateHosts(arg1:string,arg2:string):Promise<Array<mapview.MapNode>>;

export function AssignIP(arg1:string,arg2:string):Promise<string>;

export function CancelScan():Promise<void>;

export function Connect(arg1:main.ConnectRequest):Promise<escli.ClusterInfo>;

export function DeleteDevice(arg1:string):Promise<void>;

export function DeviceHints(arg1:string):Promise<Array<main.Hint>>;

export function DismissHint(arg1:string):Promise<void>;

export function ExportImage(arg1:string):Promise<string>;

export function ExportMap(arg1:string,arg2:string):Promise<string>;

export function Legend():Promise<Array<main.LegendItem>>;

export function ListDevices():Promise<devices.Registry>;

export function ListSnapshots():Promise<Array<snapshot.ArtifactEntry>>;

export function LoadDriftModel(arg1:string,arg2:string):Promise<mapview.Model>;

export function LoadModel(arg1:string):Promise<mapview.Model>;

export function LoadReconcileModel(arg1:string,arg2:string):Promise<mapview.Model>;

export function PickAssetCSV():Promise<string>;

export function RunScan(arg1:main.ScanRequest):Promise<scan.Result>;

export function SaveDevice(arg1:string,arg2:devices.Device):Promise<void>;

export function SetLabels(arg1:string,arg2:Array<string>):Promise<void>;

export function SetRole(arg1:string,arg2:string):Promise<void>;

export function SuggestTags(arg1:main.TagRequest):Promise<assist.TagResult>;

export function UnassignIP(arg1:string):Promise<void>;
