// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mapview} from '../models';
import {main} from '../models';
import {escli} from '../models';
import {snapshot} from '../models';
import {scan} from '../models';
import {assist} from '../models';

export function AggregateHosts(arg1:string,arg2:string):Promise<Array<mapview.MapNode>>;

export function CancelScan():Promise<void>;

export function Connect(arg1:main.ConnectRequest):Promise<escli.ClusterInfo>;

export function ExportImage(arg1:string):Promise<string>;

export function ExportMap(arg1:string,arg2:string):Promise<string>;

export function Legend():Promise<Array<main.LegendItem>>;

export function ListSnapshots():Promise<Array<snapshot.ArtifactEntry>>;

export function LoadModel(arg1:string):Promise<mapview.Model>;

export function RunScan(arg1:main.ScanRequest):Promise<scan.Result>;

export function SuggestTags(arg1:main.TagRequest):Promise<assist.TagResult>;
